name: Jobinja Bot

on:
  schedule:
    - cron: "0 * * * *"   # هر ساعت (UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MAX_PAGES: "1"             # فقط صفحه‌ی اول
          MAX_ITEMS: "25"            # سقف پیام در هر اجرا
          SLEEP_BETWEEN_MSGS: "0.2"
        run: python bot.py
