name: Jobinja Bot

on:
  workflow_dispatch:    # اجرا دستی

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Send test via curl
        run: |
          echo "CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="✅ Test from GitHub Actions"
